### ISSUE TITLE
inappropriate use of break; outside of loops

### ISSUE THREAD

**Issue by mariev** [ABS-dev/PF#45]
warning found via R CMD check

**Comment by mariev** [comment]
Looks like error is thrown by: https://github.com/ABS-dev/PF/blob/8fc71f0ccb49050731482eebb6eae3ce35ac98e2/R/RRsc.r#L284

**Comment by TFKentUSDA** [comment]
I fixed this somewhere along the line.  Not sure where and I'm not going to hunt down the commit.
