### ISSUE TITLE
RRmpWald formula and vector methods do not return the same values

### ISSUE THREAD

**Issue by marireisdorf** [ABS-dev/PF#48]
The formula and vector methods do not return the same values if there are animals that are removed from the study and within a cluster (cage) there is not representation for both the treatment groups. In the example below, I have used the example from the help file but removed two animals.

Example:
newNew <- subset(New, !(cage==23 & tx == 'con') & !(cage==3 & tx == 'vac'))
table(newNew$cage)

RRmpWald(pos ~ tx + cluster(cage), newNew, compare = c('vac', 'con'))

thistable <- newNew %>%
  tidyr::spread(tx, pos) %>%
  dplyr::mutate(vac = factor(vac, levels = 1:0),
                con = factor(con, levels = 1:0)) %>%
  with(., table(vac, con)) 
RRmpWald(x = as.vector(thistable))

**Comment by TFKentUSDA** [comment]
Fixed with commit  89b0d458c23

**Comment by TFKentUSDA** [comment]
Fix with commit  89b0d458c23

**Comment by marireisdorf** [comment]
I've done conducted some minimal testing and seems the issues is fixed.
