### ISSUE TITLE
remove all instances of 1x1 matrix

### ISSUE THREAD

**Issue by mariev** [ABS-dev/PF#5]
R v 3.4.x+ now gives a warning when multiplying vector by 1x1 matrix.

Documented change in R 3.4.0 is:

>   Arithmetic, logic (&, |) and comparison (aka 'relational', e.g., 
     <, ==) operations with arrays now behave consistently, notably 
     for arrays of length zero. 

>   Arithmetic between length-1 arrays and longer non-arrays had 
     silently dropped the array attributes and recycled.  This now 
     gives a warning and will signal an error in the future, as it has 
     always for logic and comparison operations in these cases (e.g., 
     compare matrix(1,1) + 2:3 and matrix(1,1) < 2:3).

Minimal example:

```
> matrix(5) * 1:5
[1]  5 10 15 20 25
Warning message:
In matrix(5) * 1:5 :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.
```

Example from PF:

```
> RRor(tauWt(bird.fit))

95% t intervals on 4 df

PF 
    PF     LL     UL 
 0.500 -0.583  0.842 

      mu.hat    LL     UL
txcon  0.733 0.943 0.3121
txvac  0.367 0.752 0.0997
Warning message:
In qt(q, degf) * sqrt(var.log.r) :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

**Comment by mariev** [comment]
When arithmetic between length-1 arrays and non-arrays have been completely updated (in future versions of R) for consistency with logical and comparison operators, expected behavior is:

``` r
> matrix(5) ==  1:5
Error: dims [product 1] do not match the length of object [5]

> matrix(5) &  1:5
Error: dims [product 1] do not match the length of object [5]

```

**Comment by mariev** [comment]
Does not appear that R-core has turned this into a hard error. Defer debugging until adoption of 3.6.x or later.

## R .5.3
```r
> R.version.string
[1] "R version 3.5.3 (2019-03-11)"
> matrix(5) * 1:5
[1]  5 10 15 20 25
Warning message:
In matrix(5) * 1:5 :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.
```

## R 3.6.0
```r
> R.version.string
[1] "R version 3.6.0 (2019-04-26)"
> matrix(5) * 1:5
[1]  5 10 15 20 25
Warning message:
In matrix(5) * 1:5 :
  Recycling array of length 1 in array-vector arithmetic is deprecated.
  Use c() or as.vector() instead.
```

**Comment by TFKentUSDA** [comment]
Commit 8abaa233 fixed this issue.
