### ISSUE TITLE
Why is `x` and `xtable` different in RRmpWald for vector entry vs. matrix data entry?

### ISSUE THREAD

**Issue by mariev** [ABS-dev/PF#7]
The following code appears to be original (from RRmp.r in 2010 which was the ancestor of RRmpWald.r):
[lines 71-89](https://github.com/ABS-dev/PF/blob/19800c17a729ed0cc7461ff314a348a7684e6450/R/RRmpWald.r#L72)

```r
else if(is.matrix(x)){
  if(!all(dim(x) == 2)){
    stop('Table dimensions must be 2 x 2\n')
  } else {
    xtable <- x
    x <- c(x)
  }
} else if(is.vector(x)){
  if(length(x) != 4){
    stop('Vector length must be 4\n')
  }
  xtable <- matrix(x, 2, 2, byrow = T)
}
```

However, if we use the vector example from the help page, `x = c(2, 9, 1, 6)` the vector clause evaluates to the following:

```r
x <- c(2, 9, 1, 6) ## user input
xtable <- matrix(x, 2, 2, byrow = T) ## RRmpWald.r line 88
x
# [1] 2 9 1 6
xtable
#     [,1] [,2]
# [1,]    2    9
# [2,]    1    6
```
If we use the matrix value of `xtable` above as the input then we get the following:

```r
x <- matrix(c(2, 9, 1, 6), 2, 2, byrow = TRUE) ## user input
xtable <- x ## RRmpWald.r line 81
x <- c(x) ## RRmpWald.r line 82
x
# [1] 2 1 9 6
xtable
#     [,1] [,2]
# [1,]    2    9
# [2,]    1    6
```

**Comment by mariev** [comment]
Current performance:

```r

## Case 1
RRmpWald(x = c(2, 9, 1, 6))

# PF 
# 95% interval estimates
#
#    PF    LL    UL 
# 0.727 0.124 0.915 

# Case 2
RRmpWald(x = matrix(c(2, 9, 1, 6), 2, 2, byrow = TRUE)
+ )

# PF 
# 95% interval estimates
#
#      PF      LL      UL 
#  -2.667 -10.778  -0.141 

# Case 3
RRmpWald(x = matrix(c(2, 1, 9, 6), 2, 2, byrow = TRUE))

# PF 
# 95% interval estimates
# 
#   PF    LL    UL 
# 0.727 0.124 0.915 
```

**Comment by DaveSiev** [comment]
Looks like
xtable <- matrix(x, 2, 2, byrow = T)
should be changed to
xtable <- matrix(x, 2, 2, byrow = FALSE)

**Comment by DaveSiev** [comment]
I meant it should be changed in the function

**Comment by mariev** [comment]
So a user could enter:

```r
RRmpWald(x = matrix(c(2, 9, 1, 6), 2, 2, byrow = TRUE))
```
or

```r
RRmpWald(x = c(2, 9, 1, 6))
```
and expect the same result? Is this consistent with how we structure elsewhere for RR estimates?

**Comment by DaveSiev** [comment]
That's the idea.

**Comment by bwoerth** [comment]
Consensus seems that working with the formula or the vector would work out.  Especially, if we can make it clear in the help file what the order is for the vector.  Perhaps including the square matrix for visualization.  Another thought, would using a named vector?  Then they could put the digits in any order in the vector as long as they were named appropriately.

**Comment by mariev** [comment]
Usage will be updated to:

```
RRmpWald(pos ~ tx + cluster(cage), New, compare = c('con', 'vac'))

# PF 
# 95% interval estimates
#
#    PF    LL    UL 
# 0.550 0.183 0.752 

require(magrittr)
thistable <- New %>%
  tidyr::spread(tx, pos) %>%
  dplyr::mutate(vac = factor(vac, levels = 1:0),
    con = factor(con, levels = 1:0)) %>%
  with(., table(vac, con)) 
thistable
#    con
# vac  1  0
#   1  7  2
#   0 13  4
as.vector(thistable)
# [1]  7 13  2  4

RRmpWald(x = as.vector(thistable))

# PF 
# 95% interval estimates
#
#    PF    LL    UL 
# 0.550 0.183 0.752 
```

see https://github.com/ABS-dev/PF/compare/82ae6949f7425fdc04a9f8bf2d7b8cac828b7c1e...bug/issue-6
